version: '3.4'
services:
  backend:
    build: .
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=Some

volumes:
  postgres_data:

