version: '3.4'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      .env
  backend:
    build: .
    depends_on:
      db
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_SQLITE_NAME=d${DB_SQLITE_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TOKEN_SECRET_KEY=${TOKEN_SECRET_KEY}
      - TOKEN_ALGORITHM=${TOKEN_ALGORITHM}
    env_file:
      .env

volumes:
  postgres_data:

