version: '3.4'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=User
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=Some
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_TYPE=2
      - DB_SQLITE_NAME=db.db
      - DB_HOST=127.0.0.1
      - DB_USERNAME=User
      - DB_PASSWORD=Admin
      - DB_PORT=5432
      - DB_NAME=Some
      - TOKEN_SECRET_KEY=
      - TOKEN_ALGORITHM


volumes:
  postgres_data:

